### ISSUE TITLE
Zip File is Invalid

### ISSUE THREAD

**Issue by michaelbinks** [niawdeleon/google-apps-scripts#1]
I have just tried to use the script and everything appears to work and a zip file allAttachments.zip is downloaded in the browser.

However upon attempting to open the zip file I get a the following errors:

Windows: Windows cannot open the folder. The compressed (zipped) Folder [file name] is invalid

7zip: Can not open file [file name] as archive

Please can you lend some advice?

**Comment by niawdeleon** [comment]
Hi Michael, which version are you using? The current script no longer tries to download the zip file directly but instead saves it to your Google Drive because the direct download no longer works.

**Comment by niawdeleon** [comment]
Here's the link to the latest script. It will request access to your Google Drive and save a zip file called downloadAttachments.zip there. https://script.google.com/macros/s/AKfycbxdKI2h6QLrnDjtEOLfZT3Y32JrZzJqtaDSuGd9buAZDbQ6Dysj/exec

**Comment by michaelbinks** [comment]
Thanks Niaw, the latest version worked first time.

Good work!
